steps:
  - name: hashicorp/terraform:1.9.8
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        cd ${_TF_DIR}
        terraform init -input=false
        terraform validate
        terraform apply -input=false -auto-approve -var="project_id=$PROJECT_ID"
    secretEnv: ['SSH_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/tf-modules-deploy-key/versions/latest
      env: 'SSH_KEY'

options:
  logging: CLOUD_LOGGING_ONLY